# Generated by Django 3.1.5 on 2023-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmssceneappliancesdetails',
            name='componet_name',
            field=models.CharField(max_length=23),
        ),
    ]
