# Generated by Django 3.1.5 on 2023-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0004_auto_20230518_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsuserareacardslist',
            old_name='card_type',
            new_name='card_slug',
        ),
    ]
