# Generated by Django 3.1.5 on 2023-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_auto_20230518_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsdeviceinformation',
            name='is_used',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=23),
        ),
        migrations.AlterField(
            model_name='bmssubareamaster',
            name='devices_details',
            field=models.ManyToManyField(limit_choices_to={'devices_details__is_limit': False}, to='Device.BmsDeviceInformation'),
        ),
    ]
