# Generated by Django 3.1.5 on 2023-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0007_auto_20230518_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmssubareamaster',
            name='devices_details',
            field=models.ManyToManyField(limit_choices_to={'is_used': 'no'}, to='Device.BmsDeviceInformation'),
        ),
    ]
