# Generated by Django 4.1.7 on 2023-05-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0011_alter_bmssubareamaster_devices_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsuserareacardslist',
            name='card_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bmsuserareacardslist',
            name='column_no',
            field=models.IntegerField(default=1),
        ),
    ]
