# Generated by Django 4.1.7 on 2023-05-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0012_bmsuserareacardslist_card_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsuserareacardslist',
            old_name='devices_details',
            new_name='device_details',
        ),
    ]
