# Generated by Django 3.1.5 on 2023-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0013_rename_devices_details_bmsuserareacardslist_device_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsaccesscontrolrfidmaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsareamaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsbuildingmaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsdepartmentmaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsdeviceinformation',
            name='device_type',
            field=models.CharField(blank=True, choices=[('LED', 'LED'), ('AC', 'AC'), ('TV', 'TV'), ('CURTAIN', 'CURTAIN'), ('PROJECTOR', 'PROJECTOR'), ('AVR', 'AVR'), ('MP', 'MP'), ('BRP', 'BRP'), ('STB', 'STB'), ('CAMERA', 'CAMERA'), ('SPEAKER', 'SPEAKER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bmsdeviceinformation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsdevicestatushistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsdevicetypemaster',
            name='device_type_slug',
            field=models.CharField(choices=[('LED', 'LED'), ('AC', 'AC'), ('TV', 'TV'), ('CURTAIN', 'CURTAIN'), ('PROJECTOR', 'PROJECTOR'), ('AVR', 'AVR'), ('MP', 'MP'), ('BRP', 'BRP'), ('STB', 'STB'), ('CAMERA', 'CAMERA'), ('SPEAKER', 'SPEAKER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bmsdevicetypemaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsfloormaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmshistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmslocker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmssettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmssubareamaster',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bmsuserareacardslist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
