# Generated by Django 3.1.5 on 2023-05-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0014_auto_20230526_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsuserareacardslist',
            old_name='card_type',
            new_name='card_title',
        ),
    ]
