# Generated by Django 4.1.7 on 2023-05-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0016_alter_bmsaccesscontrolrfidmaster_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bmsuserareacardslist',
            table='bms_user_area_cards_list',
        ),
    ]
