# Generated by Django 4.1.7 on 2023-05-30 13:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0017_alter_bmsuserareacardslist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmsScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(blank=True, max_length=100)),
                ('operation_type', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('devices_details', models.ManyToManyField(blank=True, null=True, to='Device.bmsdeviceinformation')),
            ],
            options={
                'db_table': 'bms_scenes',
            },
        ),
        migrations.CreateModel(
            name='BmsTriggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(blank=True, choices=[('Event', 'Event'), ('Schedule', 'Schedule')], max_length=100)),
                ('trigger_data', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('scene_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.bmsscenes')),
            ],
            options={
                'db_table': 'bms_triggers',
            },
        ),
    ]
