# Generated by Django 4.1.7 on 2023-05-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0018_bmsscenes_bmstriggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmssubareamaster',
            name='devices_details',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_used': 'No'}, to='Device.bmsdeviceinformation'),
        ),
        migrations.AlterField(
            model_name='bmstriggers',
            name='trigger_data',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
