# Generated by Django 4.1.7 on 2023-05-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0019_alter_bmssubareamaster_devices_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmstriggers',
            old_name='scene_id',
            new_name='scene_details',
        ),
        migrations.AlterField(
            model_name='bmsscenes',
            name='devices_details',
            field=models.ManyToManyField(blank=True, to='Device.bmsdeviceinformation'),
        ),
    ]
