# Generated by Django 4.1.7 on 2023-06-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0021_alter_bmssubareamaster_devices_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmssubareamaster',
            name='devices_details',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_used': 'No'}, to='Device.bmsdeviceinformation'),
        ),
    ]
