# Generated by Django 4.1.7 on 2023-06-06 04:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0022_alter_bmssubareamaster_devices_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsscenes',
            name='devices_details',
        ),
        migrations.RemoveField(
            model_name='bmsscenes',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='bmsareamaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsbuildingmaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsfloormaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsscenes',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmssubareamaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmstriggers',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.CreateModel(
            name='BmsSceneAppliancesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_slug', models.CharField(max_length=23)),
                ('operation_type', models.CharField(max_length=23)),
                ('operation_value', models.CharField(max_length=23)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('is_deleted', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmsdeviceinformation')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_appliance_details', to='Device.bmsscenes')),
            ],
            options={
                'db_table': 'bms_scene_appliances_details',
            },
        ),
    ]
