# Generated by Django 4.1.7 on 2023-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0022_alter_bmssubareamaster_devices_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsareamaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsbuildingmaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsfloormaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmsscenes',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmssubareamaster',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
        migrations.AddField(
            model_name='bmstriggers',
            name='is_deleted',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=23),
        ),
    ]
