# Generated by Django 4.1.7 on 2023-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0023_remove_bmsscenes_devices_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmstriggers',
            name='scene_details',
        ),
        migrations.AlterField(
            model_name='bmstriggers',
            name='trigger_data',
            field=models.JSONField(),
        ),
    ]
