# Generated by Django 4.1.7 on 2023-06-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0023_bmsareamaster_is_deleted_and_more'),
        ('Device', '0024_remove_bmstriggers_scene_details_and_more'),
    ]

    operations = [
    ]
