# Generated by Django 4.1.7 on 2023-06-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0027_alter_bmsareamaster_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmssceneappliancesdetails',
            name='device_type_slug',
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AlterField(
            model_name='bmssceneappliancesdetails',
            name='operation_type',
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AlterField(
            model_name='bmssceneappliancesdetails',
            name='operation_value',
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
