# Generated by Django 3.1.5 on 2023-06-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0001_initial'),
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsusersdetail',
            name='locker_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_locker', to='Device.bmslocker'),
        ),
        migrations.AddField(
            model_name='bmsusersdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='Authenticate.bmsuser'),
        ),
        migrations.AddField(
            model_name='bmsuserhasareaacces',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmsbuildingmaster'),
        ),
        migrations.AddField(
            model_name='bmsuserhasareaacces',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmsdeviceinformation'),
        ),
        migrations.AddField(
            model_name='bmsuserhasareaacces',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmsfloormaster'),
        ),
        migrations.AddField(
            model_name='bmsuserhasareaacces',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmssubareamaster'),
        ),
        migrations.AddField(
            model_name='bmsuserhasareaacces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsuser'),
        ),
        migrations.AddField(
            model_name='bmsuser',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_role', to='Authenticate.bmsrole'),
        ),
        migrations.AddField(
            model_name='bmsuser',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_use_type', to='Authenticate.bmsusertype'),
        ),
        migrations.AddField(
            model_name='bmsrolesdevicesinformation',
            name='device_information_data',
            field=models.ManyToManyField(to='Device.BmsDeviceInformation'),
        ),
        migrations.AddField(
            model_name='bmsrolesdevicesinformation',
            name='role_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsrole'),
        ),
        migrations.AddField(
            model_name='bmsrole',
            name='device_data',
            field=models.ManyToManyField(blank=True, to='Device.BmsDeviceInformation'),
        ),
        migrations.AddField(
            model_name='bmsrole',
            name='modules_permission',
            field=models.ManyToManyField(blank=True, to='Authenticate.BmsModuleMaster'),
        ),
    ]
