# Generated by Django 3.1.5 on 2023-05-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_auto_20230517_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsuser',
            name='role_id',
        ),
    ]
