# Generated by Django 3.1.5 on 2023-05-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0004_remove_bmsuser_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsrolesdevicesinformation',
            name='updatated_date',
        ),
    ]
