# Generated by Django 3.1.5 on 2023-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0007_auto_20230518_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsrole',
            old_name='modules_id',
            new_name='modules_data',
        ),
        migrations.RenameField(
            model_name='bmsuser',
            old_name='user_type',
            new_name='user_type_data',
        ),
        migrations.RenameField(
            model_name='bmsusersdetail',
            old_name='department_id',
            new_name='department_data',
        ),
        migrations.RenameField(
            model_name='bmsusersdetail',
            old_name='locker_id',
            new_name='locker_data',
        ),
        migrations.RenameField(
            model_name='bmsusersdetail',
            old_name='user_id',
            new_name='user_data',
        ),
        migrations.RenameField(
            model_name='bmsusertype',
            old_name='type_name',
            new_name='role_name_data',
        ),
        migrations.RenameField(
            model_name='bmsuserwallet',
            old_name='user_id',
            new_name='user_data',
        ),
    ]
