# Generated by Django 3.1.5 on 2023-05-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0008_auto_20230518_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsrolesdevicesinformation',
            old_name='device_information_id',
            new_name='device_information_data',
        ),
        migrations.RenameField(
            model_name='bmsrolesdevicesinformation',
            old_name='role_id',
            new_name='role_data',
        ),
        migrations.RenameField(
            model_name='bmsrolesdevicesinformation',
            old_name='subarea_id',
            new_name='subarea_data',
        ),
    ]
