# Generated by Django 4.1.7 on 2023-05-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0010_alter_bmsmodulemaster_id_alter_bmsrole_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsusertype',
            old_name='role_name_data',
            new_name='role_data',
        ),
    ]
