# Generated by Django 4.2.1 on 2023-05-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0010_alter_bmsaccesscontrolrfidmaster_id_and_more'),
        ('Authenticate', '0011_rename_role_name_data_bmsusertype_role_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='department_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_department', to='Device.bmsdepartmentmaster'),
        ),
        migrations.AlterField(
            model_name='bmsusertype',
            name='role_data',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_roles', to='Authenticate.bmsrolesdevicesinformation'),
        ),
    ]
