# Generated by Django 4.2.1 on 2023-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0010_alter_bmsaccesscontrolrfidmaster_id_and_more'),
        ('Authenticate', '0012_alter_bmsusersdetail_department_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsrolesdevicesinformation',
            name='subarea_data',
        ),
        migrations.AddField(
            model_name='bmsrolesdevicesinformation',
            name='subarea_data',
            field=models.ManyToManyField(blank=True, null=True, to='Device.bmssubareamaster'),
        ),
    ]
