# Generated by Django 4.1.7 on 2023-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0013_remove_bmsrolesdevicesinformation_subarea_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsrolesdevicesinformation',
            name='subarea_data',
        ),
    ]
