# Generated by Django 4.1.7 on 2023-05-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0013_rename_devices_details_bmsuserareacardslist_device_details'),
        ('Authenticate', '0015_bmsuser_role_id_alter_bmsuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsrole',
            name='device_information_data',
            field=models.ManyToManyField(to='Device.bmsdeviceinformation'),
        ),
    ]
