# Generated by Django 3.1.5 on 2023-05-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0017_auto_20230526_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsrole',
            old_name='modules_data',
            new_name='modules_permission',
        ),
    ]
