# Generated by Django 3.1.5 on 2023-05-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0014_auto_20230526_1423'),
        ('Authenticate', '0018_auto_20230526_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmsrole',
            name='device_information_data',
        ),
        migrations.AddField(
            model_name='bmsrole',
            name='device_data',
            field=models.ManyToManyField(to='Device.BmsDeviceInformation'),
        ),
    ]
