# Generated by Django 4.1.7 on 2023-05-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0020_alter_bmsmodulemaster_id_alter_bmsrole_device_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsuser',
            name='user_type_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_use_type', to='Authenticate.bmsusertype'),
        ),
    ]
