# Generated by Django 4.1.7 on 2023-05-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0016_alter_bmsaccesscontrolrfidmaster_id_and_more'),
        ('Authenticate', '0021_alter_bmsuser_user_type_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsusersdetail',
            old_name='birthday',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='address',
            field=models.TextField(max_length=2321, null=True),
        ),
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='locker_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bms_locker', to='Device.bmslocker'),
        ),
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='user_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='Authenticate.bmsuser'),
        ),
    ]
