# Generated by Django 4.1.7 on 2023-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0024_bmsuser_is_deleted_bmsuserhasareaacces_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmsuservehiclesdetail',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=23),
        ),
        migrations.AlterField(
            model_name='bmsuser',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=23),
        ),
        migrations.AlterField(
            model_name='bmsuserhasareaacces',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=23),
        ),
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='has_vehicle',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=23),
        ),
        migrations.AlterField(
            model_name='bmsusersdetail',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=23),
        ),
        migrations.AlterField(
            model_name='bmsuservehiclesdetail',
            name='is_ev',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=23),
        ),
    ]
