# Generated by Django 4.1.7 on 2023-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0025_bmsuservehiclesdetail_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsuser',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=23),
        ),
    ]
