# Generated by Django 4.1.7 on 2023-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0027_bmsusertype_has_role_alter_bmsuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsusertype',
            name='has_role',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=23),
        ),
    ]
