# Generated by Django 4.1.7 on 2023-06-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0028_alter_bmsusertype_has_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsuser',
            old_name='role_data',
            new_name='role_id',
        ),
    ]
