# Generated by Django 4.1.7 on 2023-06-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0029_rename_role_data_bmsuser_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsuser',
            old_name='user_type_data',
            new_name='user_type_id',
        ),
    ]
